### ISSUE TITLE
Content multiplicity

### ISSUE THREAD

**Issue by brianaAtWork** [FihoFi/ntm_common_xml#10]
I don't see the value of having a NTM not having a content [0..*]

**Comment by FihoFi** [comment]
That's because you were not at the workshop :)

**Comment by FihoFi** [comment]
Due to the system with NtM, sometimes a notice (espescially T or P) could simply be cancelling another one. In that case the content is the cancellation, and actual content is not needed.

**Comment by brianaAtWork** [comment]
>That's because you were not at the workshop :)

thank you for not leaving it at this...i am sorry i missed the workshop for many reasons.
