### ISSUE TITLE
noticeDatePublished grouping

### ISSUE THREAD

**Issue by brianaAtWork** [FihoFi/ntm_common_xml#18]
It seems pretty likely that the entire contents of the NTM file will all have the same noticeDatePublished (possibly even consistently the same date the file is created). For one hundred notices per file it would be nice to not have to repeat the date published for every single notice and instead have it just under the notices element.

Is this possible?

**Comment by perro75** [comment]
The assumtion of all notices in the entire file having the same noticeDatePublished is false. A dataset of notices could be any subset of notices.  In the case of a booklet, it is possible the date will be the same for many or all notices, but even in this case it is not necessary so as some countries use web-based systems where notices are published on a per-day basis. The dataset could also be a collecion of notices published within a full year or for the lifetime of a given product. In  the latter cases the dates would most likely differ within the dataset.

**Comment by FihoFi** [comment]
The above assumption is not correct. The noticeDatePublished should be the actual date the given notice was published. Even though in some cases a given dataset may contain data with similar dates, this is not always the case.
