### ISSUE TITLE
Clarification on intended use

### ISSUE THREAD

**Issue by brianaAtWork** [FihoFi/ntm_common_xml#2]
I would like to see some clarification on the intended use for area vs. region vs vicinity within the NoticeToMariner type.  Perhaps an ontology/hierarchy would help in the definition:
biggest to smallest boundary of space:
area, region, vicinity

**Comment by FihoFi** [comment]
This is a concept used by several HO:s. I have asked for further clarification.

**Comment by brianaAtWork** [comment]
Your pointing me to S-4 in another post helped me understand this part, and I will include what I found for a paper trail on the details of the issues being raised.

https://www.iho.int/iho_pubs/standard/S-4/S4%20V4-6-0_ENG_April16.pdf
**B-630.4 Arrangement of NM**
b) General region (normally one of the following categories): Ocean/Sea or Country name (see
B-631.3).
c) Sub-region (for example: coast; gulf; island; river).
d) Specific location (for example: port name; terminal). 

It would be nice if the comments in the XSD reflected this for clarity...since the labels used in the UML (area, region and vicinity) don't follow the naming in the S-4.
