### ISSUE TITLE
EAP file in other formats to work with?

### ISSUE THREAD

**Issue by brianaAtWork** [FihoFi/ntm_common_xml#5]
Hi, I do not have Enterprise Architect is there any way you could post an .xmi file (I think I can use this one)? (I am using the Free StarUML btw)

**Comment by FihoFi** [comment]
If you wish, I could see what EA is able to export. Currently though, the EAP- file is modeled such, that the XSD can be generated and the model maintained from within the UML-model. In order for changes to be merged into the data model, I guess changes hs to be made into the EAP- project.

**Comment by FihoFi** [comment]
[CommonNtmXml_schema.zip](https://github.com/FihoFi/ntm_common_xml/files/2632901/CommonNtmXml_schema.zip)

**Comment by brianaAtWork** [comment]
Yeah, I downloaded all of that already, but don't have anything to work with the EAP file...if you could convert it to something else that Star might ingest I can do another version based on your current model without having to redo it all...but I need to work on it to get it organized ...I'm a visual learner/worker.

**Comment by FihoFi** [comment]
The link above **does** contains the exported XMI- file you asked for.. (despite the similarity in naming.)

**Comment by brianaAtWork** [comment]
when I downloaded that file it only contained an XM**L** file...

that would be capital 'L' for 'Lost' not capital 'I' for 'Ice-hole-to-jump-in-when-not-cold-enough-in-FI'...
