### ISSUE TITLE
Producer Code type

### ISSUE THREAD

**Issue by brianaAtWork** [FihoFi/ntm_common_xml#7]
It appears (from the sample files) that the producer code type should be a number (int) and not a text type.

**Comment by FihoFi** [comment]
producingAgencyS62 in NoticeToMarinerList IS of type int (in the UML anyway). Are you referring to something else?

**Comment by brianaAtWork** [comment]
Sorry, I was looking at the UML on the wiki...It is shown as text here:
http://wp12183585.server-he.de/npubwiki/wiki/images/4/4e/UML_NtM_conceptual_structure.png
