### ISSUE TITLE
externalContentFileFormatEnum

### ISSUE THREAD

**Issue by brianaAtWork** [FihoFi/ntm_common_xml#9]
it seems JPEG should also be added to the list since it is also allowed in the graphicContentFileFormatEnum ...and since PNG is in the ENUM list already.

**Comment by FihoFi** [comment]
JPEG for SYMBOL format has not been requested by any HO. Do you know of someone using this file format for SYMBOLS? There is a wish to keep the allowed formats to the minimum needed, but of course it could be added if actually used.
